# In this directory, run the following command to build/deploy this builder.
# `gcloud builds submit . --config=cloudbuild.yaml`

steps:
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/$PROJECT_ID/kubails-builder:latest", "-t", "gcr.io/$PROJECT_ID/kubails-builder:1.0.0", "."]

images:
    - "gcr.io/$PROJECT_ID/kubails-builder:1.0.0"
    - "gcr.io/$PROJECT_ID/kubails-builder:latest"
