apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
    name: letsencrypt-production
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: {{cookiecutter.domain_owner_email}}
        privateKeySecretRef:
            name: letsencrypt-production
        solvers:
        - dns01:
            clouddns:
                serviceAccountSecretRef:
                    name: clouddns-service-account
                    key: service-account.json
                project: {{cookiecutter.gcp_project}}
          selector: {}  # Match all domains
