---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{cookiecutter.project_name}}
  namespace: cert-manager
spec:
  dnsNames:
  - {{cookiecutter.domain}}
  - "*.{{cookiecutter.domain}}"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: {{cookiecutter.project_name}}-tls
